config/routes.rb
Mpc::Application.routes.draw do

  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'flyby2/search' => 'flyby2#search'
  get 'flyby2/orbit_params/:designation' => 'flyby2#orbit_params'
  post 'orbit_diagrams/static_image' => 'orbit_diagrams#static_image'

  post 'subscribe', controller: :subscriptions, action: :subscribe, as: :subscribe
  get 'unsubscribe', controller: :subscriptions, action: :unsubscribe, as: :unsubscribe
  get 'dmp/archives', controller: :dmp, action: :archive, as: :archives
  get 'dmp/draft', controller: :dmp, action: :draft, as: :draft

  resources :sources, only: [:index] do
    member do
      get :latest
    end
  end

  get '/dmp' => 'dmp#index', as: 'current_dmp'

  resources :editions, only: [:index, :new, :create, :edit, :update, :show] do
    collection do
      get :current
      get :draft
      get 'day(/:publish_date)', action: :day, as: :day
    end

    member do
      put :share
      put :publish
    end
  end

  root :to => 'mpc#index'
  get 'mpc' => 'mpc#index'
  get 'db_search' => 'db_search#index'
  get 'light_curve' => 'light_curve#index'
  get 'summary' => 'mpc#summary'
  get 'neocp_obs' => 'neocp_obs#index'
  get 'neos' => 'neos#index'
  get 'obs_request' => 'obs_request#index'
  get 'submit_obs' => 'submit_obs#index'
  get 'header' => 'mpc#header'
  get 'dependencies' => 'mpc#dependencies'
  get 'footer' => 'mpc#footer'
  get 'wrapper' => 'mpc#wrapper'
  get 'ws' => 'ws#index'

  get 'iau/MPCORB/CometEls.txt'              => 'downloads#CometEls'
  get 'iau/Ephemerides/Comets/Soft00Cmt.txt' => 'downloads#Soft00Cmt'
  get 'iau/Ephemerides/Comets/Soft01Cmt.txt' => 'downloads#Soft01Cmt'
  get 'iau/Ephemerides/Comets/Soft02Cmt.txt' => 'downloads#Soft02Cmt'
  get 'iau/Ephemerides/Comets/Soft03Cmt.txt' => 'downloads#Soft03Cmt'
  get 'iau/Ephemerides/Comets/Soft04Cmt.txt' => 'downloads#Soft04Cmt'
  get 'iau/Ephemerides/Comets/Soft05Cmt.txt' => 'downloads#Soft05Cmt'
  get 'iau/Ephemerides/Comets/Soft06Cmt.txt' => 'downloads#Soft06Cmt'
  get 'iau/Ephemerides/Comets/Soft07Cmt.txt' => 'downloads#Soft07Cmt'
  get 'iau/Ephemerides/Comets/Soft08Cmt.txt' => 'downloads#Soft08Cmt'
  get 'iau/Ephemerides/Comets/Soft09Cmt.txt' => 'downloads#Soft09Cmt'
  get 'iau/Ephemerides/Comets/Soft10Cmt.txt' => 'downloads#Soft10Cmt'
  get 'iau/Ephemerides/Comets/Soft11Cmt.txt' => 'downloads#Soft11Cmt'
  get 'iau/Ephemerides/Comets/Soft12Cmt.txt' => 'downloads#Soft12Cmt'
  get 'iau/Ephemerides/Comets/Soft13Cmt.txt' => 'downloads#Soft13Cmt'
  get 'iau/Ephemerides/Comets/Soft14Cmt.txt' => 'downloads#Soft14Cmt'
  get 'iau/Ephemerides/Comets/Soft15Cmt.txt' => 'downloads#Soft15Cmt'
  get 'iau/Ephemerides/Comets/Soft16Cmt.txt' => 'downloads#Soft16Cmt'

  match ':controller(/:action(/:id))(.:format)'
  match '/:id' => 'high_voltage/pages#show', :as => :static, :via => :get

  namespace :ws do
    resources :defaults => { :format => 'xml' }
  end
end

app/controllers/dmp_controller.rb
class DmpController < ApplicationController
  include CanCan::ControllerAdditions
  respond_to :json, :html

  def index
  end

  def draft
    @edition = Edition.draft
    authorize!(:manage, @edition)
  end

  def testemail
  	@edition = Edition.current
  	user = User.last
  	UserMailer.daily_newspaper(user, @edition).deliver
  	# UserMailer.verify_email().deliver
  end
end

app/views/dmp/archive.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="description" content="Daily Minor Planet archive page">
    <meta name="keywords" content="archive, calendar">
    <!-- Latest compiled and minified CSS -->
    <link media="all" rel="stylesheet" href="/css/all-ae-full.css">
    <link rel="stylesheet" type="text/css" href="/css/bootstrap.customized.min.css">
    <!-- Upload Image module -->
    <link rel="stylesheet" type="text/css" href="/css/jasny-bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/css/dmp_style.css" />
	<title>Editor View - Daily Minor Planet</title>
</head>
<body>
<style>
<style>

</style>
<div id="dmp-editor-wrapper">
    <div id="newspaperContainer">
    	<a href="<%= draft_path %>" style="color:#0C69E6;margin-bottom:30px;display:block;line-height:34px;"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span>&nbsp;Back to Draft for tomorrow</a>

        <section id="editorContainer">
            <div class="header" style="border-bottom: 2px solid #A7A9AC;">
                <img src="/images/title.png">
                <div class="subHeaderline" style="font-size:28px;color:#04519B">ARCHIVE</div>
            </div>
            <div class="bodyContainer dmp-archive-body">
            	<div id="dmp-archive-explanation">
            		You can review previous newspapers by clicking a day in the calendar. The color in the calendar represents the total number of shares through social media and email on that day. Darker color means more shares took place than lighter one. The newspaper will appear on the right side in an email format.</div>
            	<div id="dmp-archive-calendarContent-wrapper" style="margin:0 auto;text-align:center">
            		<div id="dmp-archive-calendar-wrapper" style="width:30%;min-height:300px;display:inline-block;">
		            	<div id="dmp-archive-calendar" ></div>
		            	<div id="dmp-archive-sharelegend" style="margin-top:50px;text-align:left;">Shares:<div id="dmp-archive-calendar-legend"></div></div>
					</div>
		        	<div id="dmp-archive-preview" style="width:60%; max-width:1000px;">
						<div id="dmp-wrapper" style="margin:30px 0; min-height:850px; height:auto; font-family: 'PT Sans', sans-serif;color:#333333">
						    <div id="newspaperContainer" style="padding:0px; margin:0px 15px auto; position: relative; ">
						        <div style="margin: 0 auto;background: #F4F4E2;box-shadow: 0 0 10px rgba(0,0,0,0.3);position: relative;width: 100%;padding: 10px 0 50px 0;">
						            <div class="header" style="width: 100%;text-align: center;padding-bottom: 0px;font-weight: bold;margin: 0 auto;border:none;">
						                <div class="subHeaderline" style="width: 100%;border-bottom: 2px solid #414042;position: relative;padding: 0px 0 2px 0px;margin-bottom: 20px;">
						                    <div class="dates" style="text-align: center;display: inline-block;font-size: 1.5em; color: black; padding-top: 0.5em;">
						                    	Daily Minor Planet at
						                        <span class="dayofweek"></span>,
						                        <span class="month"></span>
						                        <span class="day"></span>,
						                        <span class="year"></span>
						                    </div>
						                </div>
						            </div>
						            <div class="bodyContainer" style="width: 90%;min-height: 650px;vertical-align: top;margin: 0 auto;text-align: justify;">
						                <div class="contents" style="vertical-align: top;display: inline-block;width: 100%;height: auto;margin: 0 auto;padding-left:0px">
						                    <div class="heroline" style="font-size: 1.2em;font-weight: bold;margin-bottom: 10px;">NEW NEAR EARTH ASTEROID FLYBY!</div>
                                <div style="position:relative">
						                    <div class="mobile-diagram" style="display: block;width: 100%;height: 400px;background-color: #08002A;margin-bottom: 20px;background-position:50% 50%;background-repeat:no-repeat;">
                                </div>
                                 
						                    </div>
						                    <div class="flybyTitle" style="font-size: 1.2em;font-weight: bold;margin-bottom: 16px;"></div>
						                    <div class="flybyContents" style="font-size: 1em;margin-bottom: 30px;"></div>
						                    <div class="storyTitle" style="font-size: 1.2em;font-weight: bold;margin-bottom: 16px;"></div>
						                    <div class="storyContents" style="font-size: 1em;margin-bottom: 30px;"></div>
						                </div>
						            </div>
						        </div>
						    </div>
						</div>
		        	</div>
	        	 </div>
            </div>
            <a href="#" class="back-to-top"><span class="glyphicon glyphicon-arrow-up" aria-hidden="true"></span></a>
        </section>
    </div>
</div>
</body>
</html>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
<!-- Upload Image module -->
<script src="/js/jasny-bootstrap.min.js"></script>
<script src="/js/newspaper.js"></script>

<!-- D3 Calendar -->
<script src="http://d3js.org/d3.v3.min.js"></script>
<script src="http://d3js.org/colorbrewer.v1.min.js"></script>
<script src="https://d3js.org/d3-time-format.v2.min.js"></script>

<script type="text/javascript">

function chartRender(winWidth){
    var offsetWidth = (winWidth<1500) ? 135 : 0
    var offsetHeight = (winWidth<1500) ? 230 : 0

    var margin = {top: 0, bottom: 0, left: 0, right:0};

    var width = 435 - margin.left - margin.right - offsetWidth,
      height = 600 - margin.top - margin.bottom + offsetHeight,
      cellSize = 16; // cell size

    var no_months_in_a_row = Math.floor(width / (cellSize * 7 + 30));
    var shift_up = cellSize * 2;

    // TIME
    var day = d3.time.format("%w"), // day of the week
        day_of_month = d3.time.format("%e") // day of the month
        day_of_year = d3.time.format("%j")
        week = d3.time.format("%U"), // week number of the year
        month = d3.time.format("%m"), // month number
        year = d3.time.format("%Y"),
        formatDayofWeek = d3.time.format("%A"),
        formatMonth = d3.time.format("%B"),
        formatDay = d3.time.format("%d"),
        percent = d3.format(".1%"),
        format = d3.time.format("%Y-%m-%d");

    var parseTime = d3.timeParse("%Y-%m-%d");

    // pull yesterday newspaper as a default
    var today = new Date();
    today.setDate(today.getDate() - 1);
    var yesterday = format(today);
    pullNewspaper(yesterday);

    var svg = d3.select("#dmp-archive-calendar").selectAll("svg")
        .data(d3.range(year(new Date),+year(new Date)+1))
      	.enter()
        .append("svg")
      	.attr("id","svg")
	      .attr("width", width + margin.left + margin.right)
	       .attr("height", height + margin.top + margin.bottom)
        .attr("class", "RdYlGn")
        .attr("transform", "translate(" + margin.left + "," + margin.top + ")")
  	    .append("g")

    var rect = svg.selectAll(".day")
        .data(function(d) {
          return d3.time.days(new Date(d, 0, 1), new Date(d + 1, 0, 1));
        })
      .enter().append("rect")
        .attr("class", "day")
        .attr("width", cellSize)
        .attr("height", cellSize)
        .attr("x", function(d) {
          var month_padding = 1.2 * cellSize*7 * ((month(d)-1) % (no_months_in_a_row));
          return day(d) * cellSize + month_padding;
        })
        .attr("y", function(d) {
          var week_diff = week(d) - week(new Date(year(d), month(d)-1, 1) );
          var row_level = Math.ceil(month(d) / (no_months_in_a_row));
          return (week_diff*cellSize) + row_level*cellSize*8 - cellSize/2 - shift_up;
        })
        .datum(format);

    var month_titles = svg.selectAll(".month-title")  // Jan, Feb, Mar and the whatnot
          .data(function(d) {
            return d3.time.months(new Date(d, 0, 1), new Date(d + 1, 0, 1)); })
        .enter().append("text")
          .text(monthTitle)
          .attr("x", function(d, i) {
            var month_padding = 1.2 * cellSize*7* ((month(d)-1) % (no_months_in_a_row));
            return month_padding;
          })
          .attr("y", function(d, i) {
            var week_diff = week(d) - week(new Date(year(d), month(d)-1, 1) );
            var row_level = Math.ceil(month(d) / (no_months_in_a_row));
            return (week_diff*cellSize) + row_level*cellSize*8 - cellSize - shift_up;
          })
          .attr("class", "month-title")
          .attr("d", monthTitle);

    var year_titles = svg.selectAll(".year-title")  // Jan, Feb, Mar and the whatnot
          .data(function(d) {
            return d3.time.years(new Date(d, 0, 1), new Date(d + 1, 0, 1)); })
        .enter().append("text")
          .text(yearTitle)
          .attr("x", function(d, i) { return width/2 - 50; })
          .attr("y", function(d, i) { return cellSize*5.5 - shift_up*1.5; })
          .attr("class", "year-title")
          .attr("d", yearTitle);

    //  Tooltip Object
    var tooltip = d3.select("#dmp-editor-wrapper")
      .append("div").attr("id", "tooltip")
      .style("position", "absolute")
      .style("z-index", "10")
      .style("visibility", "hidden")
      .text("a simple tooltip");

/****
  // For local testing, use fixed data set
	// data format in data.csv
	// Date,share
	// 2010-10-01,232
  d3.csv("data.csv", function(error, csv) {
    var data = d3.nest()
          .key(function(d) { return d.Date; })
          .rollup(function(d) { return d[0].shares; })
          .map(csv);

    console.log("processed data reading");
***/

  var today = new Date();
  // today.setDate(today.getDate() - 1);
  var fromDate = today.getFullYear() + "-01-01";
  var toDate = today.getFullYear() + "-" + (today.getMonth()+1) + "-" + today.getDate();
  var archiveURL = "/editions.json?from=" + fromDate + "&to=" + toDate;

  // Should retrieve newspaper history list:  id, date, share
  // {"id": 5, "publish_date": "2016-07-24T10:00:00Z", "shares": 20}

  d3.json( archiveURL, function(error, csv) {
	  var data = d3.nest()
	        .key(function(d) { return d.publish_date.substring(0,10); })
          .rollup(function(d) { return ""+d[0].shares })
	        .map(csv);

		csv.forEach(function(d) {
		    d.shares = +d.shares;
		});

		var max = d3.max(csv, function(d) { return d.shares; });

		var colors = d3.scale.quantize()
			  .domain([0,max])
	    	.range(colorbrewer.YlGnBu[9]);

		var formats = {
		    threedigits: d3.format('3f')
		};

		var legend = d3.select('#dmp-archive-calendar-legend')
		  	.append('ul')
		    .attr('class', 'list-inline');

		var keys = legend.selectAll('li.key')
		    .data(colors.range());

		keys.enter().append('li')
		    .attr('class', 'key')
		    .style('border-top-color', String)
		    .text(function(d) {
		        var r = colors.invertExtent(d);
		        return formats.threedigits(r[0]);
		    });

		rect.filter(function(d) {return d in data; })
			  .style('fill', function(d) { return colors(data[d]); })
		      .select("title")
		      .text(function(d) { return data[d]; });

	    //  Tooltip
	    rect.on("mouseover", mouseOver);
	    rect.on("mouseout", mouseOut);

	    //  Select Newspaper
	    rect.on("click", mouseClick);

	    function mouseOver(d) {
	        tooltip.style("visibility", "visible");
	        var percent_data = (data[d] !== undefined) ? data[d] : 0;
	        var purchase_text = d + ": " + percent_data;

	        tooltip.transition()
	                    .duration(200)
	                    .style("opacity", .9);
	        tooltip.html(purchase_text)
	                    .style("left", (d3.event.pageX)+30 + "px")
	                    .style("top", (d3.event.pageY) + "px");
	    }

	    function mouseOut (d) {
	      tooltip.transition()
	              .duration(500)
	                .style("opacity", 0);
	        var $tooltip = $("#tooltip");
	        $tooltip.empty();
	    }

	    function mouseClick() {
		     var date = $(this)[0].__data__;
         console.log("archive date:", date);
			   pullNewspaper(date);
		  }
    });

    function dayTitle (t0) {
      return t0.toString().split(" ")[2];
    }
    function monthTitle (t0) {
      return t0.toLocaleString("en-us", { month: "long" });
    }
    function yearTitle (t0) {
      return t0.toString().split(" ")[3];
    }
}

function pullNewspaper(date){

    console.log( "date: ", date );

    // Create a pulling newspaper from DB.
    getNewspaperByDay(date);

    /*
    var parseTime = d3.timeParse("%Y-%m-%d");
    // date change
	  $('#dmp-archive-preview .dayofweek').html(formatDayofWeek(parseTime(date)));
		$('#dmp-archive-preview .month').html(formatMonth(parseTime(date)));
		$('#dmp-archive-preview .day').html(formatDay(parseTime(date)));
		$('#dmp-archive-preview .year').html(year(parseTime(date)));
    */
		// content change
}

//scroll to top
var amountScrolled = 300;

$(window).scroll(function() {
    if ( $(window).scrollTop() > amountScrolled ) {
        $('a.back-to-top').fadeIn('slow');
    } else {
        $('a.back-to-top').fadeOut('slow');
    }
});
$('a.back-to-top').click(function() {
    $('html, body').animate({
        scrollTop: 0
    }, 700);
    return false;
});

// Render Calendar Correctly
$(document).ready(function() {
  var winWidth = window.innerWidth;
  chartRender(winWidth);
});


</script>